[package]
name = "mlua-utils"
version = "0.1.0"
edition = { workspace = true }
homepage = "https://git.sr.ht/~ioiojo/meka/tree/master/item/mlua-utils"
readme = "README.md"
description = "Utility functions for mlua"

[features]
default = []
mlua-external = []
mlua-lua54 = ["mlua/lua54"]
mlua-lua53 = ["mlua/lua53"]
mlua-lua52 = ["mlua/lua52"]
mlua-lua51 = ["mlua/lua51"]
mlua-luajit = ["mlua/luajit"]
mlua-luajit52 = ["mlua/luajit52"]
mlua-luau = ["mlua/luau"]
mlua-luau-jit = ["mlua/luau-jit"]
mlua-luau-vector4 = ["mlua/luau-vector4"]
mlua-module = ["mlua/module"]
mlua-vendored = ["mlua/vendored"]

[dependencies]
mlua = { workspace = true }

[dev-dependencies]
fennel-mount = { path = "../fennel-mount", default-features = false, features = ["fennel160", "mlua-lua54", "mlua-vendored"] }
fennel-utils = { path = "../fennel-utils", default-features = false, features = ["mlua-lua54", "mlua-vendored"] }
mlua-utils = { path = ".", default-features = false, features = ["mlua-lua54", "mlua-vendored"] }
